  on:
    pull_request:
  jobs:
    pr-validate:
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-dotnet@v3
          with:
            dotnet-version: '8.0.x'
        - run: |
            dotnet restore
            dotnet build
          working-directory: src